services:
  traefik:
    image: traefik:v2.4
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./dynamic:/etc/traefik/dynamic:ro
  blue:
    image: ghcr.io/greydwarf/blue:latest

  green:
    image: green


