services:
  blue:
    image: ghcr.io/greydwarf/first-hello:main
    container_name: blue
    ports:
      - '8001:8000'
    environment:
      - EXAMPLE=production
    restart: unless-stopped

  green:
    image: ghcr.io/greydwarf/first-hello:main
    container_name: green
    ports:
      - '8002:8000'
    environment:
      - EXAMPLE=production
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - blue
      - green
    restart: unless-stopped
